In [39]:
using LinearAlgebra

In [40]:
m = [1 2 3
    4 5 6
    7 8 9
    10 11 12]

4×3 Matrix{Int64}:
  1   2   3
  4   5   6
  7   8   9
 10  11  12

In [41]:
LinearAlgebra.sum(m, dims=1)

1×3 Matrix{Int64}:
 22  26  30

In [42]:
LinearAlgebra.sum(m, dims=2)

4×1 Matrix{Int64}:
  6
 15
 24
 33

In [43]:
function LASUM(m)
    row = size(m, 1)
    col = size(m, 2)
    sumrow = zeros(eltype(m), (row,1))
    sumcol = zeros(eltype(m), (1, col))
    for i=1:row
        for j=1:col
            sumrow[i,1] = sumrow[i,1] + m[i,j]
        end
    end
    for j=1:col
        for i=1:row
            sumcol[1,j] = sumcol[1,j] + m[i,j]
        end
    end
    d = Dict()
    d["row"] = sumrow
    d["col"] = sumcol
    return d
end

LASUM (generic function with 1 method)

In [44]:
result = LASUM(m);

In [45]:
result["col"]

1×3 Matrix{Int64}:
 22  26  30

In [46]:
result["row"]

4×1 Matrix{Int64}:
  6
 15
 24
 33